-- NOTE: This script drops all tables
--       * USE WITH CAUTION *
DROP TABLE CUSTOMER CASCADE constraints;
DROP TABLE VEHICLETYPE CASCADE constraints;
DROP TABLE VEHICLE CASCADE constraints;
DROP TABLE RESERVATION CASCADE constraints;
DROP TABLE RENTAL CASCADE constraints;
DROP TABLE RETURNCAR CASCADE constraints;